### ISSUE TITLE
Issue with webhook callback

### ISSUE THREAD

**Issue by larsnikander** [vendrcontrib/vendr-payment-provider-reepay#4]
Hi

We are having an issue with the webhook call back from Reepay after upgrading til vendr 1.4.1, it seems like it doesn't recognize the "Invoice" parameter of the body as orderNumber, which it did earlier. Is there a workaround, do we need to downgrade or is this something that will be fixed soon?

The stack trace:
`{
    "message": "An error has occurred.",
    "exceptionMessage": "Value cannot be null.\r\nParameter name: orderNumber",
    "exceptionType": "System.ArgumentNullException",
    "stackTrace": "   at Vendr.Core.AssertionExtensions.MustNotBeNull[T](T param, String paramName)\r\n   at Vendr.Core.AssertionExtensions.MustNotBeNullOrEmpty(String param, String paramName)\r\n   at Vendr.Core.Web.PaymentProviders.OrderReference..ctor(Guid orderId, String orderNumber)\r\n   at Vendr.Core.Web.OrderReferenceExtensions.GenerateOrderReference(OrderReadOnly order)\r\n   at Vendr.Core.Web.Controllers.VendrPaymentController.Callback(IPaymentProvider paymentProvider, OrderReference orderReference)\r\n   at Vendr.Core.Web.Controllers.VendrPaymentController.HandleRequestWithoutOrder(String paymentProviderAlias, Guid paymentMethodId, Func`3 handler)\r\n   at Vendr.Core.Web.Controllers.VendrPaymentController.Callback(String vendrPaymentProviderAlias, Guid vendrPaymentMethodId)\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_2.<GetExecutor>b__2(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()"
}`

**Comment by bjarnef** [comment]
@larsnikander thanks for reporting - sounds strange it should be affected by an upgrade to Vendr v1.4.1 though.
Which version of Vendr was it running on previous?

Could you check if the payment has these meta data?
I recall these are stored an an JSON object in Reepay:

```
{
   "orderReference":  "",
   "orderId": "",
   "orderNumber": ""
}
```

https://github.com/vendrcontrib/vendr-payment-provider-reepay/blob/dev/src/Vendr.Contrib.PaymentProviders.Reepay/ReepayCheckoutPaymentProvider.cs#L71-L76

Do you see any error regarding payments in checkout or only in callback from webhook event?

**Comment by larsnikander** [comment]
Hi Bjarne

I can't find the metadata in the json object on reepay no, so this might be the issue. 

On reviewing our git I also see that we actually added Reepay after upgrading to 1.4.1 where the webhooks were correctly triggered, so my guess now is that we have a wrong configuration somewhere. The data sent from Reepay is the same back when the webhooks were working, but I did not check the reepay json model back then.

**Comment by bjarnef** [comment]
You should be able to find the metadata under an invoice (payment) via the button on top right: **Actions > Metadata**

![image](https://user-images.githubusercontent.com/2919859/109532071-04066b00-7ab9-11eb-9920-66426a14cdbe.png)

Furthermore I wonder if there is something configurated in the project globally regarding routing since the stacktrace mention `AuthorizationFilterAttribute`.

**Comment by larsnikander** [comment]
Okay, it does seem like it has the metadata then on the ones that are failing and the orderNumber does seem to match the ones that we are trying to finalize. But I found an interesting behaviour which I think is due to how we have designed the checkout, which might have caused the issue.

We have a detached headless cms instance which is responsible for 3 sites, of which this shop is one of them. This means that we have to interface with vendr and umbraco through api calls which are mostly timed by the frontend. In the final call where we generate the payment form we also save a few things to the order, to pick up any last minute changes. I think this design is the culprit, because saving the order does seem to run asynchronous and I think the order might get a new ordernumber during or after the form has been generated.

I think I have managed to change it now so it's reliable by splitting the two processes up so orders aren't saved during the generation of the payment form.

**Comment by bjarnef** [comment]
Oh, that sounds like an interesting use-case and probably tricky one as well :)
Great you managed to track down the culprit and hopefully it will work going forward.
Let me know if there are something else not working as expected or something which need to be enhanced or feel free to fork the project or submit a PR 👍 

Furthermore I am sure @mattbrailsford would be interested in knowing about this specific site using Vendr as commerce. I know he plans to add a "Cases" section to https://vendr.net
Also it would be interesting to know more about which payment providers are the most popular ones used in stores based on Vendr 😁 🚀
