### ISSUE TITLE
Continue Url not utilized after upgrade to Vendr.net 1.5

### ISSUE THREAD

**Issue by larsnikander** [vendrcontrib/vendr-payment-provider-reepay#5]
First of all I do realize that this is a bit premature to send an Issue, since the repo is not updated to support vendr 1.5 as of writing, but we have upgraded the rest of the website and now the continue url isn't utilized on the reepay payment window. 

Is this something that will be resolved in an upcoming version and if so, is there an estimate on the release?

Webhooks and the order flow seems to work as before, but we would like the customer to be transferred back to the website as before.

**Comment by bjarnef** [comment]
I haven't tested Reepay with v1.5 yet, but I don't think there should be changed how `continueUrl` is returned from Vendr.
https://github.com/vendrcontrib/vendr-payment-provider-reepay/blob/dev/src/Vendr.Contrib.PaymentProviders.Reepay/ReepayCheckoutPaymentProvider.cs#L128

As a recall Reepay payment window shows a "Continue" button after payment and clicking this, would redirect to the Accept URL.

What happens you click the continue button from the payment window?

**Comment by larsnikander** [comment]
Hi Bjarne

Thank you for the reply. It's quite mysterious, since we haven't changed anything in backoffice, so the continue url should be the same, do you know if there is a way to check the parameters passed to reepay? The changelog on Vendr doesn't mention any changes to the parameters either, so we are searching for a needle in a haystack. I think we will revert Vendr back to 1.4 and hope that it will solve the issue for now.

**Comment by bjarnef** [comment]
@larsnikander is this continue URL in Vendr a relative or absolute URL?
Do you use another route for backoffice than `/umbraco`, which is configurable, but Vendr didn't support that until v1.6.0, but since it worked to you previous I guess this isn't the issue here.
Some payment gateways allow to see logs of the requests, but as far I can tell Reepay doesn't have an option to see this in the UI. You could eventually contact Reepay to check to payment request - if you inform them about the Order Number .

**Comment by larsnikander** [comment]
@bjarnef we use absolute urls since the frontend is running on a different domain than backoffice, so continue and cancel urls are pointing to a different domain than where umbraco is running. Could that be an issue? I will try to contact Reepay to hear about the orders.

**Comment by bjarnef** [comment]
Maybe, but then it's strange it worked previous.
If you could check the raw payment request from Reepay it would be great to see if the "AcceptUrl" is correct. The redirect when clicking the Continue button is handled by Reepay, so it could be a change in their end.

**Comment by larsnikander** [comment]
So after talking to Reepay I found that the accept url is not send to their system after the upgrade, neither is the cancel url

Session from before the upgrade:
`{
  "id": "cs_a92a[...]c9110",
  "type": "CHARGE",
  "expires": "2021-06-25T08:58:25.874+00:00",
  "charge": "TEST-0449-0537-MW7L",
  "settle": false,
  "recurring": false,
  "customer": "3519[...]0805",
  "created": "2021-03-25T08:58:25.872+00:00",
  "currency": "DKK",
  "url": "https://checkout.reepay.com/#/cs_a92a[...]c9110",
  "phone": "53733057",
  "cancel_url": "https://[...].illumi.dk/bestil",
  "accept_url": "https://[...].illumi.dk/tak-for-bestilling",
  "payment_methods": [
    "visa",
    "dankort",
    "mc",
    "mobilepay",
    "visa_elec",
    "maestro",
    "diners"
  ]
}`

Session from after the upgrade:
`{
  "id": "cs_fb9d[...]3017f",
  "type": "CHARGE",
  "expires": "2021-07-07T07:12:19.399+00:00",
  "charge": "TEST-0461-0432-9R7R",
  "settle": false,
  "recurring": false,
  "customer": "9d9[...]06f",
  "created": "2021-04-06T07:12:19.396+00:00",
  "currency": "DKK",
  "url": "https://checkout.reepay.com/#/cs_fb9d[...]3017f",
  "phone": "00000000",
  "payment_methods": [
    "visa",
    "dankort",
    "mc",
    "mobilepay",
    "visa_elec",
    "maestro",
    "diners"
  ]
}`

**Comment by bjarnef** [comment]
Okay strange, it should be included here unless the value is `null`.
https://github.com/vendrcontrib/vendr-payment-provider-reepay/blob/dev/src/Vendr.Contrib.PaymentProviders.Reepay/ReepayCheckoutPaymentProvider.cs#L128

You could eventually fork/clone the project, compile the project in debug mode and copy the dll to tin site /bin folder.
Then on local environment go the checkout, select Reepay and continue to payment window.
If the place a breakpoint here https://github.com/vendrcontrib/vendr-payment-provider-reepay/blob/dev/src/Vendr.Contrib.PaymentProviders.Reepay/ReepayCheckoutPaymentProvider.cs#L143 you should be able to see the payment request data and the value of `continueUrl`. 

Furthermore here you should be able to see the raw payment request:
https://github.com/vendrcontrib/vendr-payment-provider-reepay/blob/5bfee0552d1e0e825170d238cadc97112705648b/src/Vendr.Contrib.PaymentProviders.Reepay/Api/ReepayClient.cs#L124

**Comment by larsnikander** [comment]
I found the error, but it wasn't in the Reepay package.

When we generate the payment form we access the PaymentProviderSettings from the payment method using camelCase, this however is now PascalCase (don't know if it is due to the new vendr update or if we have changed something) thus the ContinueUrl and CancelUrl is never fed to the form generation.

**Comment by bjarnef** [comment]
Okay great you found the root cause 👍 
Not sure if something specific has changed in PaymentProviderSettings in Vendr (not as far as I know).
However the `ReepayChargeSessionRequest` model should be fed with data and serialized according to the model properties:
https://github.com/vendrcontrib/vendr-payment-provider-reepay/blob/main/src/Vendr.Contrib.PaymentProviders.Reepay/Api/Models/ReepaySessionRequestBase.cs#L16-L20

Actually I wonder if you might have globally overwritten the JSON serializer settings, which could affect the serialization here:
https://github.com/vendrcontrib/vendr-payment-provider-reepay/blob/dev/src/Vendr.Contrib.PaymentProviders.Reepay/Api/ReepayClient.cs#L114-L120

**Comment by bjarnef** [comment]
I have just checked v1.1.0 with Vendr v1.5.3 and v1.6.0 and in both cases in seems both Accept URL and Cancel URL are populated correct.
